core/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    # path('', views.),
]

demos/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'demos'

urlpatterns = [
    path('', views.demo_list, name='demo_list'),
]

showcase/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.entry, name='main'),
    path('admin/', admin.site.urls),
    path('demos/', include('demos.urls', namespace='demos'))
]

core/models.py
from django.db import models

# Create your models here.

demos/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext as _

from .managers import CustomUserManager

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email'), unique=True)
    name = models.CharField(max_length=40, null=True, blank=True)

    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name',]

    objects = CustomUserManager()

    def __str__(self):
        return self.email

demos/views.py
from django.shortcuts import render


def demo_list(request):
    return render(request, 'demo_list.html')

showcase/views.py
from django.shortcuts import render

# Create your views here.
def entry(request):
    return render(request, 'entry.html')

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <script src="https://kit.fontawesome.com/fcad48ef90.js" crossorigin="anonymous"></script>

    {% block header_imports %} {% endblock header_imports %}
</head>
<body>
    
    <div class="framed-navigation">
        <a class="navigation-block navigation-logo-area" href="{% url 'main' %}">
            <div class="name-logo">Full Stack Software Engineer</div>
            <div class="subtitle-logo">grigori zaika</div>
        </a>
        
        <div class="navigation-block menu-block">
            <div class="menu-grid">
                <a class="menu-grid-item" href="{% url 'demos:demo_list' %}">
                    <i class="far fa-eye" aria-hidden="true"></i>
                    <div class="text-block">demos</div>
                </a>
                <a class="menu-grid-item">
                    <i class="fas fa-toilet-paper" aria-hidden="true"></i>
                    <i aria-hidden="true"></i>
                    <div class="text-block">articles</div>
                </a>
                <a class="menu-grid-item">
                    <i class="fas fa-american-sign-language-interpreting" aria-hidden="true"></i>
                    <div class="text-block">contact</div>
                </a>
                <a class="menu-grid-item">
                    <i class="fas fa-glasses"></i>
                    <div class="text-block">what's all this?</div>
                </a>
            </div>
        
        </div>
        
        <div class="navigation-block navigation-block-stub">
        </div>
    </div>
    
    <div class="gutter-left"></div>
    
    <div class="main-wrapper">
        {% block content %}
        {% endblock content %}
    </div>

    <div class="gutter-right"></div>
</body>
</html>

templates/demo_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}demos{% endblock title %}

{% block header_imports %}
<link rel="stylesheet" href="{% static 'css/demos.css' %}">
<script src="{% static 'js/demos.js' %}"></script>
{% endblock header_imports %}


{% block content %}
    <div class="demos-container">
        <div class="demo-header">
            <h2>demos</h2>
            <h5>normally, both your asses would be dead as fucking fried chicken</h5>
        </div>
        <div class="demo-item">
            <div class="demo-item-header">
                <a class="opener">
                    <i class="fas fa-window-maximize" aria-hidden="true"></i>
                </a>
                <div class="header">
                    <h3>demo item header</h3>
                </div>
            </div>
            <div class="demo-item-content">
                <form action="post">
                    <textarea name="" id="" cols="80" rows="20"></textarea>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/entry.html
{% extends 'base.html' %}
{% load static %}

{% block title %}main page{% endblock title %}

{% block header_imports %} 
{% endblock header_imports %}


{% block content %}

{% endblock content %}